# RNN
## 实例RNN对象
- 参数一：input_size 输入张量的维度
- 参数二：hidden_size 隐藏层的维度，隐藏层神经元数量
- 参数三：num_layers 隐藏层的层数

In [1]:
# 导入若干工具包
import torch
import torch.nn as nn
rnn = nn.RNN(5,6,1)

## 设定输入的张量
- 参数一：sequence_length 输入序列长度
- 参数二：batch_size 批次的样本数
- 参数三：input_size 输入张量x的维度

In [2]:
input1 = torch.randn(1,3,5)
input1

tensor([[[-1.1239,  0.0812,  0.9445,  0.4554, -0.3374],
         [ 2.0600, -1.5557,  0.2189,  1.0444,  1.0771],
         [ 0.7512, -0.9386,  0.1125,  0.8114, -0.1118]]])

## 初始化h0
- 参数一：num_layers * num_direction(层数*网络的方向数)
- 参数二：batch_size (批次的样本数)
- 参数三：hidden_size(隐藏层的维度)

In [3]:
h0 = torch.randn(1,3,6)

## 输入张量放入RNN

In [4]:
output,hn = rnn(input1,h0)

print(output)
print(output.shape)

tensor([[[-0.4167,  0.4908, -0.0222,  0.5291, -0.7819,  0.4041],
         [-0.5373, -0.1269,  0.0631, -0.4625, -0.0240, -0.7355],
         [ 0.4785, -0.2122,  0.5914,  0.3195, -0.1011, -0.0446]]],
       grad_fn=<StackBackward>)
torch.Size([1, 3, 6])


In [5]:
print(hn)
print(hn.shape)

tensor([[[-0.4167,  0.4908, -0.0222,  0.5291, -0.7819,  0.4041],
         [-0.5373, -0.1269,  0.0631, -0.4625, -0.0240, -0.7355],
         [ 0.4785, -0.2122,  0.5914,  0.3195, -0.1011, -0.0446]]],
       grad_fn=<StackBackward>)
torch.Size([1, 3, 6])


# LSTM

## torch.nn工具包中，通过torch.nn.LSTM调用

## nn.LSTM参数
- input_size:输入张量维度大小
- hidden_size:隐层张量h的维度大小
- num_layers:隐含层数量
- bidirectional:是否使用双向LSTM默认不适用

## nn.LSTM实例化参数
- 输入张量x
- h0：初始化的隐层张量h
- c0: 初始化cell状态张量c

In [6]:
import torch.nn as nn 
import torch
rnn = nn.LSTM(5,6,2)

input = torch.randn(1,3,5)
h0 = torch.randn(2,3,6)
c0 = torch.randn(2,3,6)

output,(hn,cn) = rnn(input)

In [7]:
print(output)
print(output.shape)

tensor([[[-0.0993,  0.1888,  0.0688, -0.0448, -0.0474,  0.0458],
         [-0.0769,  0.1827,  0.0554, -0.0454,  0.0100,  0.0699],
         [-0.0626,  0.2078,  0.0723, -0.0673,  0.0232,  0.0629]]],
       grad_fn=<StackBackward>)
torch.Size([1, 3, 6])


# GRU
## torch.nn工具包中，通过torch.nn.GRU调用

## nn.GRU参数
- input_size:输入张量维度大小
- hidden_size:隐层张量h的维度大小
- num_layers:隐含层数量
- bidirectional:是否使用双向GRU默认不适用

## nn.GRU实例化参数
- input :输入张量x
- h0：初始化的隐层张量h

In [8]:
# 使用示例
import torch
import torch.nn as nn

rnn = nn.GRU(5,6,2)

input = torch.randn(1,3,5)
h0 = torch.randn(2,3,6)

output,hn = rnn(input,h0)


In [9]:
output

tensor([[[ 0.0097, -0.2326, -0.1507,  0.1661,  0.3531,  0.4720],
         [-0.7199, -0.1362, -0.1142,  0.6545,  0.0543, -0.6769],
         [ 0.2696, -0.1318, -0.9313,  0.3376, -0.6559, -0.3761]]],
       grad_fn=<StackBackward>)

In [10]:
hn

tensor([[[ 0.6904, -0.5545,  0.1465, -0.7043,  0.0289,  0.3269],
         [-0.5419, -0.8835, -0.1308,  0.4300,  0.5463, -0.2583],
         [-0.6053,  0.4777,  0.7118, -0.0329, -0.1375, -0.9811]],

        [[ 0.0097, -0.2326, -0.1507,  0.1661,  0.3531,  0.4720],
         [-0.7199, -0.1362, -0.1142,  0.6545,  0.0543, -0.6769],
         [ 0.2696, -0.1318, -0.9313,  0.3376, -0.6559, -0.3761]]],
       grad_fn=<StackBackward>)