# 实例RNN对象
- 参数一：input_size 输入张量的维度
- 参数二：hidden_size 隐藏层的维度，隐藏层神经元数量
- 参数三：num_layers 隐藏层的层数

In [1]:
# 导入若干工具包
import torch
import torch.nn as nn
rnn = nn.RNN(5,6,1)

# 设定输入的张量
- 参数一：sequence_length 输入序列长度
- 参数二：batch_size 批次的样本数
- 参数三：input_size 输入张量x的维度

In [2]:
input1 = torch.randn(1,3,5)
input1

tensor([[[-0.3464,  0.8518, -2.2995,  0.4830,  1.5814],
         [ 0.2043, -1.3851,  0.0466, -0.1095, -0.8983],
         [ 0.4096, -1.2553, -0.3282,  0.3360, -0.1071]]])

# 初始化h0
- 参数一：num_layers * num_direction(层数*网络的方向数)
- 参数二：batch_size (批次的样本数)
- 参数三：hidden_size(隐藏层的维度)

In [5]:
h0 = torch.randn(1,3,6)

# 输入张量放入RNN

In [6]:
output,hn = rnn(input1,h0)

print(output)
print(output.shape)

tensor([[[ 0.2039,  0.7038, -0.5606,  0.1304, -0.8000,  0.0717],
         [-0.7743,  0.4718,  0.3208, -0.7732, -0.2663, -0.2365],
         [ 0.4058,  0.0165,  0.0714, -0.4580,  0.5429, -0.3457]]],
       grad_fn=<StackBackward>)
torch.Size([1, 3, 6])


In [7]:
print(hn)
print(hn.shape)

tensor([[[ 0.2039,  0.7038, -0.5606,  0.1304, -0.8000,  0.0717],
         [-0.7743,  0.4718,  0.3208, -0.7732, -0.2663, -0.2365],
         [ 0.4058,  0.0165,  0.0714, -0.4580,  0.5429, -0.3457]]],
       grad_fn=<StackBackward>)
torch.Size([1, 3, 6])
